solutions:
  - ok

gtests: test_mpmc_bounded
benchmarks: bench_mpmc_bounded

allow_change:
  - mpmc.h

disable_sanitizers: True

forbidden_regexp:
  - 'std::mutex'
  - '#include\s*<mutex>'

compare_to: ok
